version: '3'
services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=rsshonjoy-prod
    ports:
      - '3000:80'
